name: "Deploy on Kapstan"
description: "GitHub Action to deploy your applications directly from the Github Pipeline on Kapstan"
author: "Kapstan"
branding:
  icon: activity
  color: purple
inputs:
  application_name:
    description: "The name of the application"
    required: true
  image_tag:
    description: "The image tag you want to deploy"
    required: false
  image_repository_name:
    description: "The image repository name that this image tag belongs to"
    required: false
  kapstan_api_key:
    description: "Your Kapstan API key"
    required: true
  wait_for_deployment:
    description: "Checks for deployment status and waits till success/failure is returned"
    required: false
    default: "true"
  pre_deploy_image_tag:
    description: "The image tag for pre-deploy job if you want to deploy, sending null/blank to use the existing version"
    required: false
    default: ''
  containers:
    description: "Array of container objects with name and imageTag. Empty tags would be omitted"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.application_name}}
    - ${{ inputs.image_tag}}
    - ${{ inputs.pre_deploy_image_tag}}
    - ${{ inputs.kapstan_api_key}}
    - ${{ inputs.wait_for_deployment}}
    - ${{ inputs.containers }}
